In [1]:
#arrays in python
#numpy arrays
import numpy as np

In [4]:
#creating an array

arr=np.array([1,2,3,4,5])

#list passed

In [7]:
arr


array([1, 2, 3, 4, 5])

In [8]:
#datatype of an array


In [17]:
arr=np.array([1,2,3,4],dtype=float)

In [18]:
arr

array([1., 2., 3., 4.])

In [11]:
arr=np.array([1,2,3,4,5,'hi'])

In [12]:
arr

array(['1', '2', '3', '4', '5', 'hi'], dtype='<U11')

In [19]:
arr=np.array([1,2,3,4],dtype='string')

TypeError: data type 'string' not understood

In [20]:
arr

array([1., 2., 3., 4.])

In [21]:
arr=np.arange(10,40,2)

In [22]:
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [23]:
#(naam,index,kya hai)
np.insert(arr,5,int(40))
#shift+tab to document

array([10, 12, 14, 16, 18, 40, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [24]:
np.delete(arr,5)

array([10, 12, 14, 16, 18, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [25]:
arr


array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [26]:
np.insert(arr,0,100)

array([100,  10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,
        34,  36,  38])

In [27]:
arr
#array mei nhi aay because array mei define nhi kiya

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [28]:
arr=np.insert(arr,0,100)

In [29]:
arr

array([100,  10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,
        34,  36,  38])

In [30]:
arr=np.append(arr,69)

In [31]:
arr

array([100,  10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,
        34,  36,  38,  69])

In [32]:
arr[3]

14

In [35]:
#2-d array
#array ke andar row wise=matrices
mat=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [37]:
mat=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [38]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [39]:
print(mat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [40]:
#speed list
#pehla time import ko aur dusra uske andar ke function ko
a=[i for i in range(1,10000000)]
b=[i for i in range(10000000,20000000)]
c=[]
import time
start=time.time()
for i in range(len(a)):
    c.append(a[1]+b[1])
print(time.time()-start)

5.813088417053223


In [45]:
arr1=np.arange(10000000)
arr2=np.arange(10000000,20000000)
import time
start=time.time()
arr3=arr1+arr2
print(time.time()-start)
#numpy array is so fast

0.03199434280395508


In [42]:
5.813088/0.49782


11.677088104134024

In [43]:
5.8/.49

11.83673469387755

In [46]:
print(time.time())

1673958983.7935667


In [47]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [48]:
#how to access elemnt
mat[1]

array([5, 6, 7, 8])

In [49]:
mat[1,1]

6

In [50]:
mat[1,2]+mat[1,1]

13

In [52]:
# number se start nhi kar sakte
d3=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])

In [53]:
d3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [54]:
mat[1,1]

6

In [57]:
for i in range(3):
    print(mat[i,2])

3
7
11


In [60]:
d3=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])

In [61]:
d3[1,0]

array([ 9, 10, 11, 12])

In [62]:
d3[1,0,2]

11

In [ ]:
#task 
# 1)searching an elemnt in an array
# 2)finding largest element in a array
# 3)finding smallest number in an array
# 4)reversing an array
# 5)rotating an array from kth position