# searching an element in an array

In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4,5,6,7,8,9])

In [4]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
print(arr)

[1 2 3 4 5 6 7 8 9]


In [8]:
arr[2]

3

In [9]:
arr[5]

6

In [8]:
a=[1,2,3,4,5]
s=0
for i in a:
    if s==i:
        print("found")
return
     
print("not found")

SyntaxError: 'return' outside function (1985942864.py, line 6)

# finding largest element in an array

In [24]:
def largest(arr,n):
    max = arr[0]
    for i in range(1, n):
        if arr[i] > max:
            max = arr[i]
    return max
arr = [2,45,66]
n = len(arr)
Ans = largest(arr, n)
print("Largest in given array ", Ans)

Largest in given array  66


# finding smallest in an array

In [25]:
def smallest(arr,n):
    min = arr[0]
    for i in range (1,n):
        if arr[i] < min:
            min = arr[i]
    return min

arr=[34,23,45,55,78,12,89]
n = len(arr)
ans = smallest(arr,n)
print("smallest in given array is  ",ans)

smallest in given array is   12


# reversing an array

In [37]:
arr=np.array([1,2,3,4,5])

In [38]:
len(arr)

5

In [39]:
arr[0]

1

In [40]:
arr[1]

2

In [41]:
arr[2]

3

In [42]:
arr[3]

4

In [43]:
arr[4]

5

In [44]:
rev=np.flip(arr) 

In [45]:
print("reverse array is:",rev )

reverse array is: [5 4 3 2 1]


# rotating an element from kth position

In [18]:
def rotate(arr, n, k):
    k=k%n
    for i in range(n):
        t=arr[n-1]
        for j in range(n-1,0,-1):
            arr[j]=arr[j-1]
        arr[0]=t
    return arr
arr=[1,2,3,4,5]
print(rotate(arr, len(arr), 2))

[1, 2, 3, 4, 5]


In [1]:
import numpy as np
def rotate(arr, n, k):
    k=k%n
    for i in range(n):
        t=arr[n-1]
        for j in range(n-1,0,-1):
            arr[j]=arr[j-1]
        arr[0]=t
    return arr
arr=np.array([1,2,3,4,5])
print(rotate(arr, len(arr),2))

[1 2 3 4 5]
